export const root: string;
export const selected: string;
export const active: string;
export const disabled: string;
export const draggable: string;
export const dragIcon: string;
export const primary: string;
export const leading: string;
export const trailing: string;
